// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package context

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("../../migrations", "20180905174455-initial.sql", "\"H4sIAAAAAAAA/9xXSW/jNhS+61fwFhu1g8TZZjCXKjY9EerIqUwVmZPAERmbqCRquDjjf19Ym0lZSt2gRYDqyPe97XsLKWc8Br+kbC2woiDMHWcaQBdBgNz7BQTeHPhLBOCzt0IrsGWE8khyLWIKBg4AjAD783wEv8IAPAXeoxt8A7/Bb8AN0dLzpwF8hD4aOQBkOKWWFoLPhSAXfO9CNII/3GD64AaD2+sh8MPFYg/SkgrLQhcox1K+ckHeBH3HkkZaJEdxpFfaOj8I8M9IKkFxKq18i7hyghWNXgT9oWkW7wolMINzN1wgcPYrwSzZne2RLM25UJREWFXmvUe4Qu7jUwOfhkEAfRQ1Emf45eTSRErg+M/OAp1UH8sWI2aS7dLVxJSkRI07QyXha96lonZ5p6kYK7rmYtc+p/k6MtOpz9tsnkDmyHEAmC8D6H319xQMWhkPQQDnMID+FNrMDhgZ/l0l1poR+v8Zkp9porbmNLTjiAhW2BR87CCY9EfxBmcZTd4/CqW1g6rR1yUxB1EfL/V5TdO/1b/Tpb9Cgev5CFRpRjpjPzQFoe/9HkIwqIMfNbEOR63GryFWx5sU/tOOj3LB1wKnadn7HfwVM17V5XiNYKFMjg4ZA0Azu4KWcN9ypnDmIvhB1WgY6K9Hlf+oTHi0T+2/KU3CMqrz7jX07k1kFkySvC27Xy4X0PUbwlAQFqVImFQ0izAhgkp5sHNYDZeTu/OL84vzy2I7ECZjvqViZ6i8hd8XrifB4r7RGRWyV5ziTL/gWGlxWK22txVLWMwzoqUq/KWc0CSy2bE1HmYPPKWBzgB8RtCfmWo6/d7n6GGGpuNJuCrgL0ykr1hQ05EN35ANT6nQmYojrGRsq22pkIxnx2qTi8ubi0+T25JrumUxte7XI66vrm9u7z6ZcKzVpgeuaFIt+QqrtWG82/TYhRN3fA1vrsf399PP46srd343u5ndup8nZ8YrQwmcybraLS6UygtoLCg2b5YTZ/m0eXrzXjltqCpDnTeLYirpfhpVe75pnlpQvlGKZ19p0rBWroxa1X7ObdqxV7NbdBDecsGMrWrIjth9z6OrocDacOXpoOOuspPsfaOViC4DbSZ6N2uNaTas9ZM046+Z48yC5VPVIqb3L32CMixLbLrsFdSxWICSpI6jA/qvAAAA//+mYnMb2A0AAA==\"")
		packr.PackJSONBytes("../../migrations", "20180913140221-AddVideoTrackUniqueConstraint.sql", "\"H4sIAAAAAAAA/+LS1VXQzs1ML0osSVUILeDicg5ydQxxVQj18wwMdVXw9HNxjVAoKUpMzo4vzcssLE1V8PdTKMtMSc2PL84vLUpOjQdLaqAIZaboKBSXFKUm5sZnpmhac6FY4pJfnscFCAAA//+8qzXOdwAAAA==\"")
		packr.PackJSONBytes("../../migrations", "dbconfig.yml", "\"H4sIAAAAAAAA/6zMMQ4CMQxE0T6n8Alo6HwbbzxClrzr4DhI3B6Fjp5ynkZf8YLHOHEVNyI1cfRimk+3wn2TlMxY2cFUcH/f9Pg+k+m0R0pZXLMRlRyOH2sjQ1ff4//xTwAAAP//TU5AhLoAAAA=\"")
}
