// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package context

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
		packr.PackJSONBytes("../../migrations", "20180905174455-initial.sql", "\"H4sIAAAAAAAA/9xXW2/iOBR+z6/wW0ELVUtvM5qnlJhptDR0g7PqPEWexAVrEzvjCy3/fkVCgh2SLlvtRRoec75z+77jY+OMx+CXnK4EVgREheNMQ+giCJB7P4fAn4FggQB89pdoCTY0JTyWXIuEgIEDAE2B/fMDBL/CEDyF/qMbfgO/wm/AjdDCD6YhfIQBGjkAMJwTywvB59JQCL5LIRrD7244fXDDwe31EATRfL4DaUmEFaELVGApX7lI3wV9x5LEWmRHdeRX2vp+MOC3WCpBcC6tfsu6ihQrEr8I8kMTlmwbJ5oXXCiSxljto/mPcIncxyfgwZkbzRGYRmEIAxQ3Fmf45WQlYiVw8kenHifJYcWiqdlTW6m6pYqDuElnuGR8xbtc1LboDJVgRVZcbNvfSbGKzXb62DyBzJHjADBbhND/GuwoGLQ6HoIQzmAIgym0mR3QdPhXSqw0TcnPcybe8kxtzOFv1xGnWGHT8J/Ovcl2nKwxYyT7+ORX0Q6uxhhXPBxMfTTU32tW/qlxnS6CJQpdP0Bg32asGf2hCYgC/7cIgkFd/KipdThqzXkNsQbcpPDvDnhcCL4SOM+rUe/grzzSe12OtwYWyuTo0DEAhNkKWsbdhJlGz0Xwf1KjYaBfj33/o6rh0a61f0eajDKii+6t8+HFYwom06Jtu18s5tANGsJQGJVSZFQqwmKcpoJIeYjTAM8uJ3fnF+cX55dnpURUJnxDxNZweQ+/E66nwfJ60YwI2WvOMdMvOFFaHDapnW1JM5pwlmqpynw5T0kW2+zYHg/eA89JqBmAzwgGnumm8+99iR48NB1PomUJf6Eif8WCmIls+Dpd85wIzVQSYyUT221DhKScHbtNLi5vLj5NbiuuyYYmxLpOj7i+ur65vftkwrFW6x64Ilm2NbFaG8G7Q49dOHHH1/Dmenx/P/08vrpyZ3fejXfrfp6cGY8KJTCTtdotLpQqSmgiCDZvlhPP8mnn6d175bRDtQ/UebMoqrLul9B+zzfDUxuqJ0n5yqtCGtGqlVG72q+3dbv2/dktJwhvuKDGVjVsR+x+5I3VUGBtuOrroOOuspvsfZJViK4AbSZ6N2uNaTas9RfI46/Mcbxw8bQfETP7lz5DVZZlNlP2GupaLEBFUsenA/rPAAAA//9uhhgAtg0AAA==\"")
		packr.PackJSONBytes("../../migrations", "dbconfig.yml", "\"H4sIAAAAAAAA/6zMMQ4CMQxE0T6n8Alo6HwbbzxClrzr4DhI3B6Fjp5ynkZf8YLHOHEVNyI1cfRimk+3wn2TlMxY2cFUcH/f9Pg+k+m0R0pZXLMRlRyOH2sjQ1ff4//xTwAAAP//TU5AhLoAAAA=\"")
}
