linters-settings:
  goimports:
    local-prefixes: github.com/telly/telly
  errcheck:
    ignore: fmt:.*,AbortWithError

linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - gochecknoinits
    - goconst
    - gofmt
    - goimports
    - golint
    - gosec
    - ineffassign
    - interfacer
    - megacheck
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow
  disable:
    - unused
    - unparam

run:
  skip-files:
    - ".*-packr.go$"