#!/usr/bin/with-contenv bash

source /etc/env

echo "
RUNNING ENVIRONMENT
-----------------------------------------------
PUID           | $PUID
PGID           | $PGID
-----------------------------------------------
"
