#!/usr/bin/with-contenv bash

source /etc/env

echo "
RUNNING ENVIRONMENT
-----------------------------------------------
PUID           | $PUID
PGID           | $PGID
VERSION        | $VERSION
STREAMS        | $STREAMS
FFMPEG         | $FFMPEG
BASE           | $BASE
M3U            | $M3U
EPG            | $EPG
FILTER         | $FILTER
PERSISTENCE    | $PERSISTENCE
-----------------------------------------------
"

